-- Insert food options
INSERT INTO foods (vendor, food_name, food_id, calories, avg_rating) VALUES
('Cru5h', 'Crispy Chicken Tenders', 1, 380, NULL),
('Cru5h', 'Crispy Incogmeato Tenders', 2, 550, NULL),
('Cru5h', 'French Fried Potatoes', 3, 360, NULL),
('Cru5h', 'French Fried Tater Tots', 4, 440, NULL),
('Cru5h', 'Mozzarella Sticks', 5, 580, NULL),
('Cru5h', 'Burrito Bowl', 6, NULL, NULL),
('Cru5h', 'Quesadilla', 7, NULL, NULL),
('Cru5h', 'FUN Burger On Brioche Bun', 8, 540, NULL),
('Cru5h', 'FUN Double Burger On Brioche Bun', 9, 840, NULL),
('Cru5h', 'FUN Impossible Burger On Brioche Bun', 10, 380, NULL),
('Garbanzos', 'Bowl', 11, 160, NULL),
('Garbanzos', 'Flatbread', 12, 440, NULL),
('Garbanzos', 'Pita', 13, 440, NULL),
('Garbanzos', 'Plate', 14, 160, NULL),
('Garbanzos', 'Salad', 15, 160, NULL),
('Garbanzos', 'Laffa Wrap', 16, 490, NULL),
('Garbanzos', 'Baklava', 17, 230, NULL),
('Garbanzos', 'Falafel', 18, 60, NULL),
('Garbanzos', 'House Made Chips', 19, 530, NULL),
('Garbanzos', 'House Made Fries', 20, 530, NULL),
('Garbanzos', 'Hummus', 21, 190, NULL),
('Garbanzos', 'Pita, Side', 22, 440, NULL),
('Garbanzos', 'Seasoned Rice', 23, 110, NULL),
('Garbanzos', 'Tabbouleh', 24, 50, NULL),
('Hissho Sushi', 'Pork Gyoza Dumpling', 25, 310, NULL),
('Hissho Sushi', 'California Roll', 26, 330, NULL),
('Hissho Sushi', 'Krispy Krab Roll', 27, 410, NULL),
('Hissho Sushi', 'Nagano Special', 28, 730, NULL),
('Hissho Sushi', 'Outer Banks Roll', 29, 670, NULL),
('Hissho Sushi', 'Rainbow Roll', 30, 340, NULL),
('Hissho Sushi', 'Southern Charm Roll', 31, 410, NULL),
('Hissho Sushi', 'Spicy Roll', 32, 300, NULL),
('Hissho Sushi', 'Tempura Shrimp Roll', 33, 520, NULL),
('Hissho Sushi', 'Veggie Roll', 34, 320, NULL),
('Hissho Sushi', 'Special Cooked Combo', 35, 620, NULL);
